Exercices
readthedocs-fr/notions pull request #36
Opened 2020-08-17 19:12 UTC by Hokkaydo

- Création du dossier `exercices`
- Création du README.md français
- Création du README.md anglais
- Ajout de la première paire d'exercice/correction en français - Fonction composée

Cette PR est à titre indicatif pour marquer le début de ce dossier mais aussi et surtout pour recevoir des avis sur le premier exercice proposé. 
Je marque donc cette PR en `draft`.

2020-08-18 08:13 UTC, fusetim commented on exercices/fr/README.md
> +Les **corrections** sont données avec des explications quand c'est nécessaires.
```suggestion
Les **corrections** sont données avec des explications quand c'est nécessaire.
```
ou
```suggestion
Les **corrections** sont données avec des explications quand elles sont nécessaires.
```

2020-08-18 08:19 UTC, fusetim commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Notre méthode va traiter une condition avec la suivante, une fois qu'elles auront été composée en une nouvelle fonction, celle ci se verra ajoutée à la fin de la liste afin qu'on puisse la récupérer.
```suggestion
Notre méthode va traiter une condition avec la suivante, une fois qu'elles auront été composées en une nouvelle fonction, celle ci se verra ajoutée à la fin de la liste afin qu'on puisse la récupérer.
```

2020-08-18 08:20 UTC, fusetim commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Et voilà, notre méthodes `compose()` est terminée.
```suggestion
Et voilà, notre méthode `compose()` est terminée.
```

2020-08-18 08:23 UTC, fusetim commented on exercices/fr/java/fonction_composee/ENONCE.md
> +C'est à dire que la variable *(x)* sera affecté par la 1ère fonction, ensuite, ce n'est plus la variable qui sera affecté par la seconde fonction mais bien **le résultat** de la variable par la 1ère
```suggestion
C'est à dire que la variable *(x)* sera affectée par la 1ère fonction, ensuite, ce n'est plus la variable qui sera affectée par la seconde fonction mais bien **le résultat** de la variable par la 1ère fonction
```

2020-08-18 08:25 UTC, fusetim commented on exercices/fr/java/fonction_composee/ENONCE.md
> +Comme nous l'avons dit plus haut, la fonction `g` était le `x` de la fonction `f`.                                    Je l'ai donc simplement remplacé dans l'expression.
Strange whitespace sequence
```suggestion
Comme nous l'avons dit plus haut, la fonction `g` était le `x` de la fonction `f`.
Je l'ai donc simplement remplacé dans l'expression.
```

2020-08-18 08:26 UTC, fusetim commented on exercices/fr/java/fonction_composee/ENONCE.md
> +2. Une fois ceci fait, essayez d'étendre votre fonction à une fonction capable de prendre une infinité de fonction en paramètre et d'en sortir la fonction composée.
Strange whitespace sequence
```suggestion
2. Une fois ceci fait, essayez d'étendre votre fonction à une fonction capable de prendre une infinité de fonction en paramètre et d'en sortir la fonction composée.
*Je vous suggère de passer par une liste de fonctions en paramètre pour cette deuxième étape.*
```

2020-08-18 08:29 UTC, fusetim commented
Énoncé et correction très bien expliqués.

2020-08-18 16:19 UTC, LukaMrt commented on exercices/fr/README.md
> +Mais retenez bien une chose, il n'y a jamais qu'une seule solution possible !
Je trouve que la formulation
``Il n'y a jamais qu'une... ``
peut laisser penser qu'il n'y en a qu'une seule... Non ?
Peut être que
``Il y a toujours plusieurs solutions``
Permettrait de lever cette ambiguïté ?

2020-08-18 16:20 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +> Avant de commencer, sachez qu'il n'existe jamais qu'une seule solution.
Voir autre commentaire

2020-08-18 16:22 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/ENONCE.md
> +Soit les fonctions :
```suggestion
Soient les fonctions :
```

2020-08-18 16:23 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/ENONCE.md
> +Soit les fonctions :
Cette formulation n'est pas extrêmement rigoureuse d'un point de vue mathématiques mais je pense que c'est largement compréhensible dans ce contexte

2020-08-18 16:27 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/ENONCE.md
> +        return 3*x;
```suggestion
        return 3 * x;
```
(par cohérence avec la ligne 94)

2020-08-18 16:33 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +On va commencer par appliquer la première étape et faire une **méthode** qui peut **composer 2 fonctions** **en** **une seule**.
```suggestion
On va commencer par appliquer la première étape et faire une **méthode** qui peut **composer 2 fonctions en une seule**.
```

2020-08-18 16:35 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Vous êtes d'accord avec moi qu'une variable ou une méthode, ça a besoin de type. Tant pour se définir que pour dire à quoi on sert.
C'est vrai pour certains langages, dans certains le type n'est pas forcément explicite

2020-08-18 16:44 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +*Néanmoins, comme dit au début, toute solution qui fonctionne est une solution correcte, il n'y a pas de solution meilleure que toutes les autres Si vous avez choisi de partir sur les boucles, bien v
```suggestion
*Néanmoins, comme dit au début, toute solution qui fonctionne est une solution correcte, il n'y a pas de solution meilleure que toutes les autres. Si vous avez choisi de partir sur les boucles, bien vu, c'est déjà nickel d'être arrivé jusqu'ici. Vous avez réussi l'exercice. Mais regardez quand même ce que ça donne sous une autre forme, ça ne peut être que bénéfique* 😇
```

2020-08-18 16:45 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Quelque chose de récursif, c'est quelque chose qui fait tout le temps appel à lui même jusqu'à ce que la boucle d'appel se casse ou soit stoppée**.**
```suggestion
Quelque chose de récursif, c'est quelque chose qui fait tout le temps appel à lui même jusqu'à ce que la boucle d'appel se casse ou soit stoppée.
```

2020-08-18 16:47 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +    if(funcitons.size() == 1) {
```suggestion
    if(functions.size() == 1) {
```

2020-08-18 16:49 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +        return x -> 0; //la forme x-> y
Je pense que retourner ``x -> x`` serait plus cohérent non ? Si x est appliqué à aucune fonction, alors le retour est x

2020-08-18 17:12 UTC, Hokkaydo commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +On va commencer par appliquer la première étape et faire une **méthode** qui peut **composer 2 fonctions** **en** **une seule**.
Je n'ai pas compris le but de cette suggestion. 
Elle m'a l'air d'être similaire à la phrase déjà présente.

2020-08-18 17:14 UTC, Hokkaydo commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Vous êtes d'accord avec moi qu'une variable ou une méthode, ça a besoin de type. Tant pour se définir que pour dire à quoi on sert.
En effet, cependant, comme nous avions prévu, au début, de séparer les énoncés par langage, il n'y avait aucun problème de compréhension tant que l'on se trouve dans le dossier `java`. 
A voir

2020-08-18 17:15 UTC, Hokkaydo commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +*Néanmoins, comme dit au début, toute solution qui fonctionne est une solution correcte, il n'y a pas de solution meilleure que toutes les autres Si vous avez choisi de partir sur les boucles, bien v
Je n'ai pas compris le but de cette suggestion.
Elle m'a l'air d'être similaire à la phrase déjà présente.

2020-08-18 17:16 UTC, Hokkaydo commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +        return x -> 0; //la forme x-> y
Je voulais faire référence à la forme `x -> y` et donc ne pas renvoyer `x` mais c'est idiot en effet.

2020-08-25 11:22 UTC, LukaMrt requested changes

2020-08-25 11:22 UTC, LukaMrt commented on exercices/fr/README.md
> +- `📑` [Fonction composée](https://github.com/readthedocs-fr/notions/blob/master/exercices/fr/java/fonction_composee/ENONCE.md) - par [Alexandre Orékhoff](https://github.com/Hokkaydo)
```suggestion
- `🎯` [Fonction composée](https://github.com/readthedocs-fr/notions/blob/master/exercices/fr/java/fonction_composee/ENONCE.md) - par [Alexandre Orékhoff](https://github.com/Hokkaydo)
```

2020-08-25 11:22 UTC, LukaMrt commented on exercices/fr/README.md
> +- `📑` [Fonction composée](https://github.com/readthedocs-fr/notions/blob/master/exercices/fr/java/fonction_composee/CORRECTION.md) - par [Alexandre Orékhoff](https://github.com/Hokkaydo)
```suggestion
- `🎯` [Fonction composée](https://github.com/readthedocs-fr/notions/blob/master/exercices/fr/java/fonction_composee/CORRECTION.md) - par [Alexandre Orékhoff](https://github.com/Hokkaydo)
```

2020-08-25 11:26 UTC, LukaMrt requested changes

2020-08-25 11:26 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +        System.out.println(sValue + uValue);
```suggestion
        System.out.println(sValue.toString() + uValue.toString());
```

2020-08-25 11:36 UTC, LukaMrt requested changes

2020-08-25 11:36 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Elle signifie "Cette fonction prend une valeur x et renvoie une valeur y"
```suggestion
Elle signifie "Cette fonction prend une valeur x et renvoie une valeur y". Je vous invite à lire la fiche sur les [interfaces fonctionnelles en java](https://github.com/readthedocs-fr/notions/tree/master/java/interfaces_fonctionnelles) afin d'y voir plus clair.
```

2020-08-26 07:56 UTC, LukaMrt requested changes

2020-08-26 07:56 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +    private String```java
```suggestion
```

2020-08-26 07:56 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +    return new BiValue(size, weight);
```suggestion
public BiValue<Integer> getMeasurements() {
    return new BiValue<Integer>(size, weight);
```

2020-08-26 07:56 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +public void getIdentiy() {
```suggestion
public BiValue<String> getIdentiy() {
```

2020-08-26 07:56 UTC, LukaMrt commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Bref, les types génériques sont des types variable d'une instance de classe à l'autre **mais qui restent constants au sein d'une même instance**.
```suggestion
Bref, les types génériques sont des types pouvant varier d'une instance de classe à l'autre **mais qui restent constants au sein d'une même instance**.
```

2020-08-26 08:56 UTC, LukaMrt approved these changes
Seems good to me, @Tran-Antoine ?

2020-08-26 20:03 UTC, Tran-Antoine requested changes
A few changes and all good for me.

2020-08-26 20:03 UTC, Tran-Antoine commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Bref, les types génériques sont des types pouvant varier d'une instance de classe à l'autre **mais qui restent constants au sein d'une même instance**.
L'exemple est très clair, j'aurais simplement évité les `//getter`, `code de la classe Person` etc, ça ne coûte rien de répéter le code et je trouve que c'est plus simple pour le lecteur

2020-08-26 20:03 UTC, Tran-Antoine commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Afin de comprendre son fonctionnement, je vous suggère de jeter un coup à [cette fiche](https://github.com/readthedocs-fr/notions/tree/master/java/interfaces_fonctionnelles) sur les interfaces foncti
```suggestion
Afin de comprendre son fonctionnement, je vous suggère de jeter un coup d'oeil à [cette fiche](https://github.com/readthedocs-fr/notions/tree/master/java/interfaces_fonctionnelles) sur les interfaces fonctionnelles dont notre chère et bien-aimée interface `Function` fait partie .
```
Le pastis pour construire des phrases, c'est une mauvaise idée :D

2020-08-26 20:03 UTC, Tran-Antoine commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +Elle signifie "Cette fonction prend une valeur x et renvoie une valeur y". Je vous invite à lire la fiche sur les [interfaces fonctionnelles en java](https://github.com/readthedocs-fr/notions/tree/ma
```suggestion
Elle signifie "Cette fonction prend une valeur x et renvoie une valeur y". A nouveau, je vous invite à lire la fiche sur les [interfaces fonctionnelles en java](https://github.com/readthedocs-fr/notions/tree/master/java/interfaces_fonctionnelles) si cette syntaxe vous est inconnue.
```

2020-08-27 08:26 UTC, Tran-Antoine commented on exercices/fr/java/fonction_composee/CORRECTION.md
> +    public int getWeighr() {
```suggestion
    public int getWeight() {
```

2020-08-27 08:26 UTC, Tran-Antoine approved these changes

2020-08-27 08:32 UTC, Tran-Antoine requested changes
My mistake, there are still a few changes to apply that I missed about file tree structure

2020-08-27 17:19 UTC, Tran-Antoine approved these changes

2020-08-27 17:20 UTC, merged