feat: add `javascript/curryfication`
readthedocs-fr/notions pull request #37
Opened 2020-08-20 07:57 UTC by Aakodal

Notion sur la curryfication basée en JS

2020-08-20 08:28 UTC, Hokkaydo requested changes
Chouette fiche, bien expliquée, avec exemples.
Bon travail.

Je verrais bien, en guise de fin, une petite conclusion reprenant les principales utilités de la curryfication ainsi que quelques liens si l'envie nous prend d'aller voir plus loin.

Par ailleurs, la curryfication n'agit pas qu'en javascript. Ça pourrait être intéressant de la fiche dans un dossier `FP` comme pour la `poo`.
À voir

2020-08-20 08:28 UTC, Hokkaydo commented on javascript/curryfication/fr/CURRYFICATION.md
> +Bien que la curryfication puisse sembler aux premiers abords superflue, elle est au contraire bien utile. Elle permet notamment de simplifier le débogage (les fonctions currifiées ont pour but d'être
Je pense que ça pourrait être intéressant de détailler un peu la notion de fonction pure ainsi que les effets de bords. Pareil pour la `partial application`, même si un lien est donné, ça pourrait être sympa de résumer rapidement ce que c'est

2020-08-20 08:28 UTC, Hokkaydo commented on javascript/curryfication/fr/CURRYFICATION.md
> +Il s'agit également un des points négatifs de la curryfication : une fois curryfiée, une fonction perd la signature de ses arguments (leur nom, leur type). Assurez-vous donc d'essayer de donner un or
```suggestion
Il s'agit également d'un des points négatifs de la curryfication : une fois curryfiée, une fonction perd la signature de ses arguments (leurs noms et leurs types). Assurez-vous donc d'essayer de donner un ordre logique à vos arguments.
```

2020-08-20 08:28 UTC, Hokkaydo commented on javascript/curryfication/fr/CURRYFICATION.md
> +Bien que la curryfication puisse sembler aux premiers abords superflue, elle est au contraire bien utile. Elle permet notamment de simplifier le débogage (les fonctions currifiées ont pour but d'être
Tu parles tantôt de `fonction curyfiée`, tantôt de `fonction curifiée` + typo
```suggestion
 ## Utilité
Bien que la curryfication puisse sembler aux premiers abords superflue, elle est au contraire bien utile. Elle permet notamment de simplifier le débogage (les fonctions curryfiées ont pour but d'être dites "pures", donc qu'elles ne provoquent pas d'effet de bord et que leur valeur de retour ne dépende que des arguments fournis), améliore la lisibilité en réduisant les répétitions, et permet également d'appliquer une [partial application](https://en.wikipedia.org/wiki/Partial_application) sur une fonction à plusieurs arguments.
```

2020-08-20 08:53 UTC, Aakodal commented
J'ai ajouté ce que tu as proposé, et même si j'ai rapidement expliqué le concept de fonction pure, je pense que ce serait une bonne idée d'en faire une notion à part entière (ça reste une suggesion, étant donné que maintenant on a un dossier "functional_programming")

2020-08-20 09:10 UTC, Hokkaydo commented on functional_programming/curryfication/fr/CURRYFICATION.md
> +- de simplifier le débogage ; les fonctions curryfiées ont pour but d'être dites "[pures](https://fr.wikipedia.org/wiki/Fonction_pure)" :elles ne provoquent donc pas d'[effet de bord](https://fr.wiki
Avec ce changement de texte, ma suggestion de typo n'est plus valable.
Il faudrait rechanger `dépende` en `dépend`.
My bad

2020-08-20 09:12 UTC, Aakodal commented on functional_programming/curryfication/fr/CURRYFICATION.md
> +- de simplifier le débogage ; les fonctions curryfiées ont pour but d'être dites "[pures](https://fr.wikipedia.org/wiki/Fonction_pure)" :elles ne provoquent donc pas d'[effet de bord](https://fr.wiki
Elle m'a échappé aussi blblbl

2020-08-20 11:05 UTC, LukaMrt reviewed
Bonne fiche avec des explications claires. Je n'ai pas vu de typo après la review de @Hokkaydo. Comme je n'ai pas les connaissances pour juger le côté technique de cette fiche il faudrait que quelqu'un d'autre se prononce dessus (peut être @AntoineJT ?)

2020-08-20 11:15 UTC, Kawacrepe commented
J'ai du mal avec l'exemple que tu as fourni, je vais regarder ce weekend (pas le temps avant) pour proposer un exemple.
Car j'ai au taff, développé une "mini-librairie" de validation de formulaire, basée sur cette notion de fonction currifiée

2020-08-20 12:36 UTC, Aakodal commented
Je pense que cette notion pourrait avoir sa propre fiche, non ?

2020-08-20 14:54 UTC, fusetim commented
Si on doit parler de `function composition`, il faudra penser à relier avec l'exercice de la PR https://github.com/readthedocs-fr/notions/pull/36.

2020-08-20 16:10 UTC, Hokkaydo commented
@fusetim 
J'avais pensé à le noter puis je me suis rendu compte que, actuellement, l'exercice ne comporte qu'une forme `POO` qui ne correspond pas vraiment au style de programmation fonctionnelle présenté ici.
Mais une PR pour ajouter ça est la bienvenue évidemment.

2020-08-24 20:55 UTC, LukaMrt commented
up, @Kawacrepe tu as un peu de temps pour jeter un œil ?

2020-08-25 13:18 UTC, Kawacrepe commented
yep, je vais jeter un oeil mais je ne peux pas faire plus... bcp de travail en ce moment

2020-08-25 13:23 UTC, Kawacrepe approved these changes
LGTM, il faudrait peut-être creuser les exemples d'utilisations dans d'autres fiches et/ou exercices, j'imagine des exemples dans une application node.js, sur du vue / react etc... ça pourrait permettre de donner des cas concrets et de la valeur à l'utilisateur/lecteur de ce repo

2020-08-26 09:09 UTC, fusetim approved these changes

2020-08-27 10:14 UTC, LukaMrt approved these changes

2020-08-27 11:22 UTC, merged