fix: typo + writing some details in notions/java/interfaces_fonctionn…
readthedocs-fr/notions pull request #50
Opened 2020-09-06 04:02 UTC by Drassero

…elles/fr/INTERFACES_FONCTIONS.md

2020-09-06 11:24 UTC, Aakodal requested changes
typo

2020-09-06 11:24 UTC, Aakodal commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +  - Tout d'abord, entre les parenthèses se trouvent les paramètres de la méthode, séparés par des virgules. Ici, il n'y a qu'un seul paramètre, donc pas besoin de virgule (d'ailleurs, pour un tel cas
```suggestion
  - Tout d'abord, entre les parenthèses se trouvent les paramètres de la méthode, séparés par des virgules. Ici, il n'y a qu'un seul paramètre, donc pas besoin de virgule (d'ailleurs, dans un tel cas, les parenthèses peuvent être omises). Notez que le type des paramètres n'est pas explicité, puisqu'il est connu.
```

2020-09-06 13:24 UTC, Drassero commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +  - Tout d'abord, entre les parenthèses se trouvent les paramètres de la méthode, séparés par des virgules. Ici, il n'y a qu'un seul paramètre, donc pas besoin de virgule (d'ailleurs, pour un tel cas
Bah on peut mettre les deux

2020-09-06 16:33 UTC, Aakodal commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +  - Tout d'abord, entre les parenthèses se trouvent les paramètres de la méthode, séparés par des virgules. Ici, il n'y a qu'un seul paramètre, donc pas besoin de virgule (d'ailleurs, pour un tel cas
Je ne crois pas me tromper en disant que la seconde forme est beaucoup plus commune et sort beaucoup plus naturellement (je suis pas sûr d'avoir déjà vu "pour un tel cas" d'ailleurs...)

2020-09-06 16:46 UTC, Drassero commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +  - Tout d'abord, entre les parenthèses se trouvent les paramètres de la méthode, séparés par des virgules. Ici, il n'y a qu'un seul paramètre, donc pas besoin de virgule (d'ailleurs, pour un tel cas
Oui c'est peut être plus commun je vais mettre ça merci

2020-09-06 18:18 UTC, Aakodal approved these changes

2020-09-06 19:05 UTC, LukaMrt requested changes

2020-09-06 19:05 UTC, LukaMrt commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +Dans certains cas, il est possible de réduire cette syntaxe encore plus qu'elle ne l'est déjà. Il s'agit du cas où l'on souhaite appeler une méthode comme unique instruction de notre lambda, et que l
```suggestion
Dans certains cas, il est possible de réduire cette syntaxe encore plus qu'elle ne l'est déjà. Il s'agit du cas où l'on souhaite appeler une méthode comme unique instruction de notre lambda, et que la signature de cette méthode est la même que la signature de la méthode à implémenter (type de retour et paramètres équivalents) . Ce cas particulier s'appelle **method referencing**. Comme le cas au-dessus par exemple :

```

2020-09-06 20:20 UTC, Drassero commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +Dans certains cas, il est possible de réduire cette syntaxe encore plus qu'elle ne l'est déjà. Il s'agit du cas où l'on souhaite appeler une méthode comme unique instruction de notre lambda, et que l
Bv

2020-09-07 05:13 UTC, Aakodal requested changes
Typo

2020-09-07 05:13 UTC, Aakodal commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +Grâce aux raccourcis syntaxiques comme les lambdas et les références de méthodes, Java 8 favorise l'utilisation des interfaces fonctionnelles, permettant de stocker, en quelques sortes, une méthode s
```suggestion
Grâce aux raccourcis syntaxiques comme les lambdas et les références de méthodes, Java 8 favorise l'utilisation des interfaces fonctionnelles, permettant de stocker, en quelque sorte, une méthode sous forme de variable. En revanche, on est encore extrêmement loin de pouvoir dire que Java est un langage supportant le paradigme fonctionnel (et il ne le sera très probablement jamais), même si cet ajout est très pratique et utilisé.

```
Après recherches, et ce comme l'expression "quelques temps", " quelques sortes" est au singulier.

2020-09-07 10:49 UTC, Drassero commented on java/interfaces_fonctionnelles/fr/INTERFACES_FONCTIONNELLES.md
> +Grâce aux raccourcis syntaxiques comme les lambdas et les références de méthodes, Java 8 favorise l'utilisation des interfaces fonctionnelles, permettant de stocker, en quelques sortes, une méthode s
ça semble plus en effet merci

2020-09-07 15:48 UTC, Aakodal approved these changes

2020-09-07 18:42 UTC, LukaMrt approved these changes

2020-09-07 19:09 UTC, merged

2020-09-07 19:15 UTC, Tran-Antoine commented
Thanks for your contribution! (and shame on me for that last typo :D)