Ajout de outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
readthedocs-fr/notions pull request #54
Opened 2020-10-11 18:47 UTC by Drassero

2020-10-11 19:29 UTC, Hokkaydo requested changes
Chouette idée, ça permettra à beaucoup de découvrir les moteurs de production. 

Le texte est bien formulé (malgré quelques typos) cependant, je me demande s'il ne vaudrait pas mieux de centrer précisément cette fiche sur les moteurs de production et de créer un sous-dossier contenant une fiche par moteur (comme Gradle, Maven, SBT mais aussi NPM, Cargo, ...) 

J'ai quand même l'impression d'avoir lu une fiche me présentant plus gradle que le concept de Build Tool en général.

Ce n'est qu'une observation mais j'aimerais bien en discuter avant que la PR ne soit fusionnée.

Mais ça reste du bon travail.

2020-10-11 19:29 UTC, Hokkaydo commented on outils/README.md
> +Ce répertoire contientra la présentation de certains outils qui ne concernent pas directement du code mais qui peuvent s'avérer utiles pour la programmation. Des notions techniques par rapport à ces
```suggestion
Ce répertoire contiendra la présentation de certains outils qui ne concernent pas directement du code mais qui peuvent s'avérer utiles pour la programmation. Des notions techniques par rapport à ces outils peuvent aussi être expliquées.
```

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +## Examples d'automatisations pouvant être implémentées
```suggestion
## Exemples d'automatisations pouvant être implémentées
```

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +> Écrit par [Drassero](https://github.com/Drassero)
```suggestion
> Écrit par [Drassero](https://github.com/Drassero) \
```
Permet un retour à la ligne

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +La gestion des dépendances sur certains outils permet de construire une application en implémentant ses dépendances (e.g. librairies) grâce à une syntaxe assez simple à utiliser, par exemple en spéci
```suggestion
La gestion des dépendances sur certains outils permet de construire une application en implémentant ses dépendances (e.g. librairies) grâce à une syntaxe assez simple à utiliser, par exemple en spécifiant simplement l'identifiant du groupe proposant la dépendance, le nom de la dépendance à utiliser et sa version. Cela permet d'éviter de se compliquer la tâche lorsqu'on travaille avec différentes librairies en nous évitant de devoir les télécharger manuellement, les importer lors du lancement ou la compilation, mettre à jour la version, les ajouter à l'IDE si on utilise un IDE...
```

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +La génération de la documentation a pour but de produire la documentation de l'application pour si c'est une librairie par exemple (*JavaDoc* pour Java, *ScalaDoc* pour Scala...).
```suggestion
La génération de la documentation a pour but de produire la documentation de l'application si c'est une librairie par exemple (*JavaDoc* pour Java, *ScalaDoc* pour Scala...).
```

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +- [Gradle](https://gradle.org/) (il est pratique, c'est celui que j'utilise)
Je ne suis pas sûr que donner son avis ici est très pertinent. Ce n'est pas un blog mais un article objectif sur les builds tools. Donner les avantages et défauts de Gradle est plus approprié je pense, mais dans ce cas, il faut agir avec impartialité et également donner ceux des autres outils

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +Voici un petit exemple d'utilisation de Gradle qui, je l'espère, vous convaincra sur l'utilité des moteurs de production si vous n'êtes pas déjà convaincu.
```suggestion
Voici un petit exemple d'utilisation de Gradle qui, je l'espère, vous convaincra sur l'utilité des moteurs de production si vous ne l'êtes pas déjà.
```

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +Le fichier `build.gradle` est celui dans lequel on écrit le script Gradle et dans le dossier source (`src`), on trouve les deux modules de l'application (module principal `main` et module de test `te
```suggestion
Le fichier `build.gradle` est celui dans lequel on écrit le script Gradle et dans le dossier source (`src`), on trouve les deux modules de l'application (module principal `main` et module de test `test`). Pour plus détails, faites un tour sur [la documentation de Gradle](https://docs.gradle.org/current/userguide/userguide.html). On ne s'occupera pas ici du test de l'application, ceci est un simple tutoriel d'introduction à Gradle. Voici le code que j'ai placé à l'intérieur de App.java :
```
Cette suggestion est assez subjective. Je trouve ça plus naturel comme ça mais c'est bien évidemment très discutable

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +	// Tâche qui permet de configurer le manifest présent dans le .jar
```suggestion
	// Tâche qui permet de configurer le manifeste présent dans le .jar
```

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +		// Ajoute l'attribut 'Main-Class' avec la valeur 'com.drassero.tutorial.App' dans le manifest exporté
```suggestion
		// Ajoute l'attribut 'Main-Class' avec la valeur 'com.drassero.tutorial.App' dans le manifeste exporté
```

2020-10-11 19:29 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +    // Dépendance utilisée par la application
```suggestion
    // Dépendance utilisée par l'application
```

2020-10-11 20:54 UTC, Drassero commented
@Hokkaydo oui c'est vrai que l'introduction à gradle a pas grand chose à faire dans le même fichier mais les exemples étaient là pour exposer ce que je présente concrètement plutôt que de parler avec des phrases abstraites qu'on comprend pas forcément si on sait pas de quoi la fiche parle. Sinon merci pour les typos

2020-10-11 20:58 UTC, Hokkaydo commented
@Drassero 
Pour ne pas parler avec des mots creux, peut être rediriger directement sur les futures fiches Gradle, NPM etc ?

Je pense vraiment qu'il y a moyen d'expliciter clairement ce que permet un BuildTool sans devoir se diriger vers un cas particulier.

La longueur de la fiche n'est pas importante, tant qu'elle explique correctement son sujet.

@AntoineJT @Tran-Antoine @LukaMrt un avis ?

2020-10-11 23:39 UTC, Drassero commented
@Hokkaydo
Alors oui en fait tu as sûrement raison sur le fait qu'il faut séparer les notions dans de fichiers pour permettre en plus d'introduire des tutoriels sur différents build tools du coup j'ai séparé la fiche en deux en mettant des liens avec ancres qui mènent sur les différents tutoriels (possibilité d'introduire un nouveau lien pour chaque exemple pour chaque build tool présenté)

2021-01-18 00:39 UTC, Hokkaydo requested changes

2021-01-18 00:39 UTC, Hokkaydo commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +Voici quelques Build Tools que vous pouvez :
```suggestion
Voici quelques Build Tools que vous pourriez rencontrer :
```

2021-01-18 00:55 UTC, Drassero commented on outils/moteurs_de_production/fr/MOTEURS_DE_PRODUCTION.md
> +Voici quelques Build Tools que vous pouvez :
j'ai corrigé ça, merci de me l'avoir fait remarquer

2021-01-18 06:52 UTC, Hokkaydo approved these changes

2021-07-07 13:36 UTC, fusetim approved these changes

2021-07-07 14:26 UTC, AntoineJT commented
Cette PR traîne vraiment depuis trop longtemps et j'en suis désolé @Drassero
Plein de monde au fil du temps a trouvé que ton travail est vraiment cool donc je vais l'approve et le merge

2021-07-07 14:27 UTC, AntoineJT approved these changes

2021-07-07 14:27 UTC, merged